// <auto-generated />
namespace AlmocoAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MudancaVirtual : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MudancaVirtual));
        
        string IMigrationMetadata.Id
        {
            get { return "201811221429259_MudancaVirtual"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
